<?php

if(!class_exists('WPFEPP_Tab')){
    require_once 'class-wpfepp-tab.php';
}

class WPFEPP_Tab_Settings_List extends WPFEPP_Tab
{
	/**
	 * Class constructor. Calls the parent constructor.
	 *
	 * @var string $version Plugin version.
	 * @var string $slug Tab slug.
	 * @var string $name Tab name.
	 **/
	function __construct($version, $slug, $name) {
		parent::__construct($version, $slug, $name);
	}

	/**
	 * Registers the actions of this class with WordPress. 
	 * This function is called by add_actions of WPFEPP_Tab_Collection, which in turn is called by add_actions of WPFEPP_Plugin_Settings.
	 **/
	public function add_actions(){
		add_action( 'admin_init', array($this, 'create_options') );
	}

	/**
	 * Creates the settings section, resgisters setting and adds settings fields. Uses WordPress' settings API.
	 *
	 * @see add_settings_section()
	 * @see register_setting()
	 * @see add_settings_field()
	 **/
	public function create_options(){
		$section 		= 'wpfepp_post_list_settings_section';
		$tab 			= 'wpfepp_post_list_settings_tab';
		$option_id 		= 'wpfepp_post_list_settings';
		$curr_settings 	= get_option($option_id);
		$callback 		= array($this->renderer, 'render');
		$args 			= array('group' => $option_id, 'curr' => $curr_settings);

		add_settings_section( $section, '', array($this, 'section_callback'), $tab );

		register_setting( $tab, $option_id, array($this->validator, 'validate') );

		add_settings_field(
	        'post_list_page_len', __('Post List Page Length', 'wpfepp-plugin'), $callback, $tab, $section,
	        array_merge(
				array(
					'desc' 	=> __('Number of items to display on a single page of the post list table.', 'wpfepp-plugin'),
					'id' 	=> 'post_list_page_len',
					'type' 	=> 'text'
				),
				$args
			)
	    );
	    add_settings_field(
	        'post_list_tabs', __('Post List Tabs', 'wpfepp-plugin'), $callback, $tab, $section,
	        array_merge(
				array(
					'desc' 	=> __('Which tabs would you like to display in the post list table', 'wpfepp-plugin'),
					'id' 	=> 'post_list_tabs',
					'type' 	=> 'multicheckbox',
					'items' => array('live' => __('Live', 'wpfepp-plugin'), 'pending' => __('Pending', 'wpfepp-plugin'), 'draft' => __('Draft', 'wpfepp-plugin'))
				),
				$args
			)
	    );
	    add_settings_field(
	        'post_list_cols', __('Post List Columns', 'wpfepp-plugin'), $callback, $tab, $section,
	        array_merge(
				array(
					'desc' 	=> __('Which columns would you like to display in the post list table', 'wpfepp-plugin'),
					'id' 	=> 'post_list_cols',
					'type' 	=> 'multicheckbox',
					'items' => array('link' => __('Permalink', 'wpfepp-plugin'), 'edit' => __('Edit', 'wpfepp-plugin'), 'delete' => __('Delete', 'wpfepp-plugin'))
				),
				$args
			)
	    );
	}

	/**
	 * Outputs the contents of the tab with the help of WordPress' settings API.
	 **/
	public function display(){	    
	    ?>
	    <form method="post" action="options.php">
		    <?php
				settings_fields( 'wpfepp_post_list_settings_tab' );
				do_settings_sections( 'wpfepp_post_list_settings_tab' );
				submit_button( __('Save Settings', 'wpfepp-plugin'), 'primary', null, true );
			?>
		</form>
		<?php
	}

	public function section_callback($args){
		?>
			<p class="description"><?php printf(__('These settings are for the list tables generated by %s shortcode.', 'wpfepp-plugin'), '<code>[wpfepp_post_table]</code>'); ?></p>
		<?php
	}
}